// main.js
const { app, BrowserWindow } = require('electron');
const path = require('path');

function createWindow() {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      // Preload script can still be useful for secure IPC if needed later
      // preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false, // Keep false (safer) - bundle handles Node modules
      contextIsolation: true, // Keep true (safer)
      // webSecurity: true // Default is true, should be fine now
    },
    icon: path.join(__dirname, 'icon.jpeg') // Icon path relative to root
  });

  // --- MODIFIED LINE ---
  // Load the index.html file generated by Webpack into the 'dist' directory
  mainWindow.loadFile(path.join(__dirname, 'dist', 'index.html'));
  // --- END MODIFICATION ---

  // Optional: Open DevTools (useful for debugging the bundled code)
  // mainWindow.webContents.openDevTools();

  // Optional: Remove menu bar
  // mainWindow.setMenu(null);
}

app.whenReady().then(() => {
  createWindow();
  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});